### ISSUE TITLE
How to improve the top bar of the app?

### ISSUE THREAD

**Issue by apoorvpandey0** [MarcusNg/flutter_spotify_ui#1]
The user name comes over the text behind when scrolling down the playlist.
![asas](https://user-images.githubusercontent.com/32810722/117337344-e1c70a00-aeba-11eb-8d4d-791faa954055.png)

**Comment by MarcusNg** [comment]
You can handle this by using a ScrollController and changing the opacity of the AppBar based on the current scroll position.
I do this in the [Responsive Netflix UI Tutorial](https://www.youtube.com/watch?v=rJKN_880b-M)
